/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DataFlow_dataflow */

#ifndef _Included_DataFlow_dataflow
#define _Included_DataFlow_dataflow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DataFlow_dataflow
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DataFlow_dataflow_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
