/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FieldAccess_InstanceFieldAccess */

#ifndef _Included_FieldAccess_InstanceFieldAccess
#define _Included_FieldAccess_InstanceFieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FieldAccess_InstanceFieldAccess
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_FieldAccess_InstanceFieldAccess_accessField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
