/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_HelloWorld */

#ifndef _Included_test_HelloWorld
#define _Included_test_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
