/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StaticFieldAccess_StaticFielcdAccess */

#ifndef _Included_StaticFieldAccess_StaticFielcdAccess
#define _Included_StaticFieldAccess_StaticFielcdAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StaticFieldAccess_StaticFielcdAccess
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StaticFieldAccess_StaticFielcdAccess_accessField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
