/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BasicTypes_Prompt */

#ifndef _Included_BasicTypes_Prompt
#define _Included_BasicTypes_Prompt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BasicTypes_Prompt
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BasicTypes_Prompt_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
