/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Arrays_IntArray */

#ifndef _Included_Arrays_IntArray
#define _Included_Arrays_IntArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Arrays_IntArray
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Arrays_IntArray_sumArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
